version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/google-fonts-plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/google-fonts-plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build

workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test
